name: Build and Release Android APK

on:
  push:
    branches: [main]

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Clean and get dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Verify Java and Android setup
        run: |
          echo "Java version:"
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          echo "Flutter doctor:"
          flutter doctor -v

      - name: Build release APK
        run: |
          flutter build apk --release --verbose

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version:[ ]*//')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.get_version.outputs.version }}"
          name: "v${{ steps.get_version.outputs.version }}"
          commit: ${{ github.sha }}
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          artifactContentType: application/vnd.android.package-archive
          generateReleaseNotes: true
